### ISSUE TITLE
Format audit results

### ISSUE THREAD

**Issue by lpseodeveloper** [Logical-Position/TADAAbot#21]
Display the audit results in a nicer format:
- [x] Only display the contents of the 'data' property.
- [x] Display each datum on its own line.
- [x] "Clean it up" a.k.a remove extraneous characters, like the single quotes and commas
- [x] Substitute underscores for spaces
- [x] Sentence case

**Comment by logicalmic** [comment]
The first three items have been completed:
- [x] Only display the contents of the 'data' property.~~
- [x] Display each datum on its own line.~~
- [x] "Clean it up" a.k.a remove extraneous characters, like the single quotes and commas~~

**Comment by logicalmic** [comment]
Decided on uppercase instead of sentence case -- some terms like "GA" and "SC" looked weird as "Ga" and "Sc"
